const responses = {
    "hello": "hi there! how can i assist you today?",
    "how are you?": "i'm just a chatbot, but i'm here to help you!",
    "what is your name?": "i'm anil chatbot, your virtual assistant.",
    "bye": "goodbye! have a great day!",
    "what time is it?": "i'm not sure, but you can check your device's clock.",
    "how can i contact support?": "you can reach out to support at support@example.com.",
    "what is the weather today?": "i can't check the weather, but you can use a weather app.",
    "where are you located?": "i exist in the digital world, so i'm everywhere and nowhere!",
    "what can you do?": "i can answer questions and provide information on various topics.",
    "tell me a joke": "why don't scientists trust atoms? because they make up everything!",
    "what is your favorite color?": "i don't have personal preferences, but blue is often liked by many.",
    "can you help me with math?": "yes, i can help with basic math questions.",
    "what is the capital of france?": "the capital of france is paris.",
    "who is the president of the united states?": "as of now, the president of the united states is joe biden.",
    "how do i reset my password?": "you can reset your password by following the 'forgot password' link on the login page.",
    "what is your purpose?": "my purpose is to assist you by providing information and answering questions.",
    "what is the meaning of life?": "the meaning of life is a philosophical question that varies from person to person.",
    "how can i improve my productivity?": "you can improve productivity by setting goals, prioritizing tasks, and minimizing distractions.",
    "can you play music?": "i can't play music, but you can use a music app or streaming service.",
    "what is the latest news?": "i can't provide real-time news, but you can check news websites for the latest updates.",
    "what is the square root of 16?": "the square root of 16 is 4.",
    "how do i make a cake?": "you can find cake recipes online with detailed instructions and ingredients.",
    "what is the stock market?": "the stock market is a collection of markets where stocks (shares of ownership in businesses) are bought and sold.",
    "how do i use a computer?": "you can use a computer by turning it on, navigating the operating system, and using applications for various tasks.",
    "what is artificial intelligence?": "artificial intelligence (ai) is the simulation of human intelligence in machines programmed to think and learn.",
    "how do i start a business?": "you can start a business by creating a business plan, securing funding, and registering your business.",
    "what is a healthy diet?": "a healthy diet includes a balance of fruits, vegetables, whole grains, proteins, and healthy fats.",
    "how do i fix a bug in my code?": "you can debug your code by checking for syntax errors, reviewing logic, and using debugging tools.",
    "what is blockchain technology?": "blockchain technology is a decentralized digital ledger used to record transactions across multiple computers.",
    "how do i download an app?": "you can download an app from an app store on your device, such as the google play store or apple app store.",
    "what is your favorite food?": "i don't eat, but many people enjoy pizza.",
    "how do i write a resume?": "you can write a resume by listing your work experience, skills, education, and contact information in a clear format.",
    "what are the benefits of exercise?": "exercise improves physical health, mental well-being, and overall quality of life.",
    "how do i make a phone call?": "you can make a phone call by dialing the number on your phone and pressing the call button.",
    "what is the best way to learn a new language?": "the best way to learn a new language is through practice, immersion, and using language-learning resources.",
    "how do i back up my data?": "you can back up your data by using external storage devices or cloud storage services.",
    "what is the difference between a virus and malware?": "a virus is a type of malware that replicates itself and spreads, while malware is a broader term for any malicious software.",
    "how do i clean my computer?": "you can clean your computer by removing dust from the hardware, updating software, and running antivirus scans.",
    "what is a vpn?": "a virtual private network (vpn) is a service that encrypts your internet connection and hides your online activity.",
    "how do i set up email on my phone?": "you can set up email on your phone by adding your email account through the email app or device settings.",
    "what is a resume?": "a resume is a document that summarizes your work experience, skills, and education for job applications.",
    "how do i stay motivated?": "you can stay motivated by setting clear goals, celebrating progress, and finding inspiration from others.",
    "what is the best way to save money?": "the best way to save money is by creating a budget, tracking expenses, and setting aside a portion of your income.",
    "how do i use social media?": "you can use social media by creating accounts, posting content, and interacting with others on platforms like facebook, twitter, or instagram.",
    "what is a podcast?": "a podcast is an audio program that you can listen to on-demand, usually available as a series of episodes.",
    "how do i find a good restaurant?": "you can find a good restaurant by checking reviews online, asking for recommendations, or exploring local dining options.",
    "what are the symptoms of a cold?": "common symptoms of a cold include a runny nose, sore throat, cough, and mild fever.",
    "how do i change my email password?": "you can change your email password by accessing your account settings and following the instructions for password changes.",
    "what is machine learning?": "machine learning is a subset of artificial intelligence that involves training algorithms to learn from data and make predictions.",
    "how do i cook rice?": "you can cook rice by boiling it with water, following the instructions on the rice package for proportions and cooking time.",
    "what is a domain name?": "a domain name is a web address used to identify a website on the internet.",
    "how do i create a website?": "you can create a website by choosing a domain name, selecting a web hosting service, and designing the site using website builders or coding.",
    "what is a database?": "a database is an organized collection of data that can be accessed, managed, and updated.",
    "how do i use a search engine?": "you can use a search engine by typing keywords into the search bar and reviewing the results.",
    "what is cloud computing?": "cloud computing is the delivery of computing services over the internet, such as storage, processing power, and software.",
    "how do i write a cover letter?": "you can write a cover letter by addressing it to the employer, explaining your qualifications, and expressing your interest in the job.",
    "what is a smartphone?": "a smartphone is a mobile phone with advanced features such as internet access, apps, and a touch screen.",
    "how do i set up a wifi network?": "you can set up a wifi network by configuring your router and connecting devices to the network using the wifi settings.",
    "what is a search engine?": "a search engine is a tool that helps you find information on the internet by searching for keywords.",
    "how do i create a strong password?": "you can create a strong password by using a mix of letters, numbers, and special characters and avoiding common words.",
    "what is seo?": "search engine optimization (seo) is the practice of improving your website's visibility in search engine results.",
    "how do i update my software?": "you can update your software by checking for updates in the application or operating system settings.",
    "what is cryptocurrency?": "cryptocurrency is a digital or virtual currency that uses cryptography for security and operates independently of a central authority.",
    "how do i use a calculator?": "you can use a calculator by entering numbers and operators, then pressing the equal button to get the result.",
    "what is the internet?": "the internet is a global network of interconnected computers and servers that communicate with each other.",
    "how do i send an email?": "you can send an email by composing a message, entering the recipient's email address, and clicking the send button.",
    "what is a software update?": "a software update is a new version of a program that includes bug fixes, improvements, or new features.",
    "how do i clear my browser cache?": "you can clear your browser cache by accessing the settings or history section and selecting the option to clear cached data.",
    "what is a url?": "a uniform resource locator (url) is the address used to access a resource on the internet.",
    "how do i install an app?": "you can install an app by downloading it from an app store and following the installation instructions.",
    "what is a firewall?": "a firewall is a security system that monitors and controls incoming and outgoing network traffic.",
    "how do i set up a printer?": "you can set up a printer by connecting it to your computer or network and installing the necessary drivers.",
    "what is an email signature?": "an email signature is a block of text automatically added at the end of your emails, often including your name and contact information.",
    "how do i manage my time effectively?": "you can manage your time effectively by prioritizing tasks, creating a schedule, and setting deadlines.",
    "what is an algorithm?": "an algorithm is a step-by-step procedure for solving a problem or performing a task.",
    "how do i convert a file to pdf?": "you can convert a file to pdf by using online converters or software that supports pdf conversion.",
    "what is a spreadsheet?": "a spreadsheet is a digital tool used to organize, analyze, and store data in a tabular format.",
    "how do i change my profile picture?": "you can change your profile picture by accessing your account settings and uploading a new image.",
    "what is a cookie in web browsing?": "a cookie is a small piece of data stored on your device by a website to remember your preferences or login information.",
    "how do i create a presentation?": "you can create a presentation using software like microsoft powerpoint or google slides to design and organize your slides.",
    "what is a hyperlink?": "a hyperlink is a clickable link that directs you to another webpage or resource.",
    "how do i use a gps?": "you can use a gps by entering your destination into a navigation app or device to get directions.",
    "what is a blog?": "a blog is a website or section of a website where you can post articles or updates on various topics.",
    "how do i set up a user account?": "you can set up a user account by registering on a website or application and providing the required information.",
    "what is encryption?": "encryption is the process of converting data into a secure format to prevent unauthorized access.",
    "how do i track a package?": "you can track a package by entering the tracking number on the carrier's website or app.",
    "what is a domain registrar?": "a domain registrar is a company that manages the registration of domain names for websites.",
    "how do i use a tablet?": "you can use a tablet by tapping the touchscreen, installing apps, and navigating through the operating system.",
    "what is a server?": "a server is a computer or system that provides services or resources to other computers over a network.",
    "how do i perform a system restore?": "you can perform a system restore by using the restore feature in your operating system to return your computer to a previous state.",
    "what is the difference between ram and rom?": "ram (random access memory) is temporary storage for active processes, while rom (read-only memory) is permanent storage for system instructions.",
    "how do i reset my phone to factory settings?": "you can reset your phone to factory settings by accessing the settings menu and choosing the option to perform a factory reset.",
    "what is a chatbot?": "a chatbot is a software program designed to simulate conversation with human users.",
    "how do i organize my files?": "you can organize your files by creating folders, naming files clearly, and categorizing them based on their content.",
    "what is a url shortener?": "a url shortener is a service that converts long urls into shorter, more manageable links.",
    "how do i use a digital camera?": "you can use a digital camera by turning it on, adjusting settings, and capturing photos or videos.",
    "what is a virtual assistant?": "a virtual assistant is a digital service that helps users with tasks and information through voice or text commands.",
    "how do i upgrade my computer hardware?": "you can upgrade your computer hardware by replacing or adding components such as memory, storage, or graphics cards.",
    "what is a social media account?": "a social media account is a user profile on platforms like facebook, twitter, or instagram where you can share content and connect with others.",
    "how do i use an online forum?": "you can use an online forum by registering an account, participating in discussions, and posting questions or replies.",
    "what is a captcha?": "a captcha is a security measure used to verify that a user is human and not a bot, often involving puzzles or image recognition.",
    "how do i adjust my screen brightness?": "you can adjust your screen brightness through the display settings on your device.",
    "what is a browser extension?": "a browser extension is a small software add-on that enhances the functionality of your web browser.",
    "how do i create a database?": "you can create a database using database management software and defining tables, fields, and relationships.",
    "what is the difference between a website and a web application?": "a website is primarily for information, while a web application provides interactive features and functions.",
    "how do i install an operating system?": "you can install an operating system by using installation media (like a usb drive or disc) and following the setup instructions.",
    "what is a dns server?": "a dns server translates domain names into ip addresses so that browsers can load websites.",
    "how do i manage cookies in my browser?": "you can manage cookies in your browser's privacy or security settings.",
    "what is a cloud service?": "a cloud service provides computing resources, such as storage or processing power, over the internet.",
    "how do i update my smartphone?": "you can update your smartphone by checking for software updates in the settings menu and following the instructions.",
    "what is an api?": "an application programming interface (api) allows different software programs to communicate and interact with each other.",
    "how do i use a word processor?": "you can use a word processor by creating and editing text documents with formatting options and features.",
    "what is a task manager?": "a task manager is a tool that displays and manages running processes and applications on your computer.",
    "how do i clear my browsing history?": "you can clear your browsing history through your browser's settings or history section.",
    "what is a software license?": "a software license is a legal agreement that outlines the terms of use for a software program.",
    "how do i sync my data across devices?": "you can sync your data across devices using cloud services or synchronization features provided by your applications.",
    "what is a peer-to-peer network?": "a peer-to-peer network is a decentralized network where each computer can act as both a client and a server.",
    "how do i manage my device's storage?": "you can manage your device's storage by deleting unnecessary files, using storage optimization tools, or adding more storage.",
    "what is a user interface?": "a user interface is the part of a software application that users interact with, including visual elements and controls.",
    "how do i perform a software installation?": "you can perform a software installation by running the installer program and following the setup instructions.",
    "what is a network router?": "a network router directs data between devices on a network and connects to the internet.",
    "how do i set up parental controls?": "you can set up parental controls through your device's settings or using dedicated parental control software.",
    "what is a bandwidth?": "bandwidth is the maximum rate at which data can be transferred over a network connection.",
    "how do i troubleshoot internet issues?": "you can troubleshoot internet issues by checking your connection, restarting your router, and contacting your service provider if needed.",
    "what is a software update?": "a software update is a new version of a program that includes bug fixes, enhancements, or new features.",
    "how do i use a file compression tool?": "you can use a file compression tool to reduce the size of files by creating compressed archives.",
    "what is a digital signature?": "a digital signature is an electronic method of verifying the authenticity and integrity of a digital document.",
    "how do i use voice commands?": "you can use voice commands by speaking into a device with voice recognition capabilities and following the prompts.",
    "what is an ip address?": "an ip address is a unique numerical label assigned to each device connected to a network.",
    "how do i restore deleted files?": "you can restore deleted files from your computer's recycle bin or using file recovery software.",
    "what is a mobile app?": "a mobile app is a software application designed to run on a mobile device, such as a smartphone or tablet.",
    "how do i manage notifications?": "you can manage notifications through your device's settings or within individual applications.",
    "what is an online payment?": "an online payment is a transaction completed electronically through the internet, often using payment gateways or digital wallets.",
    "how do i use a file sharing service?": "you can use a file sharing service by uploading files to the platform and sharing the link or access with others.",
    "what is a system update?": "a system update is an upgrade to the operating system that provides new features, improvements, or security patches.",
    "how do i set up a new device?": "you can set up a new device by following the initial setup instructions and configuring your preferences.",
    "what is a 2fa?": "two-factor authentication (2fa) is a security process that requires two forms of verification to access an account.",
    "how do i recover a forgotten password?": "you can recover a forgotten password by using the 'forgot password' option on the login page and following the instructions.",
    "what is a software patch?": "a software patch is a small update that fixes specific issues or vulnerabilities in a program.",
    "how do i use a digital wallet?": "you can use a digital wallet by adding payment methods and using it to make transactions online or in stores.",
    "what is a network switch?": "a network switch is a device that connects multiple devices on a network and directs data between them.",
    "how do i set up email forwarding?": "you can set up email forwarding by configuring your email account settings to redirect messages to another address.",
    "what is an antivirus program?": "an antivirus program is software designed to detect and remove malicious software from your computer.",
    "how do i enable two-factor authentication?": "you can enable two-factor authentication through your account's security settings and follow the setup instructions.",
    "what is a virtual machine?": "a virtual machine is a software-based simulation of a physical computer that can run its own operating system and applications.",
    "how do i check my system performance?": "you can check your system performance using built-in tools or third-party software that monitors hardware and software metrics.",
    "what is a network topology?": "network topology refers to the arrangement of devices and connections in a network, affecting its performance and structure.",
    "how do i use a spreadsheet formula?": "you can use a spreadsheet formula by entering it into a cell to perform calculations based on data in other cells.",
    "what is a digital certificate?": "a digital certificate is an electronic document used to verify the identity of an individual or organization online.",
    "how do i access my cloud storage?": "you can access your cloud storage by logging into your account through a web browser or app.",
    "what is a system restore point?": "a system restore point is a snapshot of your system's configuration that you can revert to in case of issues.",
    "how do i secure my home network?": "you can secure your home network by using a strong password, enabling encryption, and keeping your router firmware updated.",
    "what is a data breach?": "a data breach is an incident where unauthorized access is gained to sensitive or confidential data.",
    "how do i use a web browser?": "you can use a web browser by entering urls, navigating websites, and utilizing features like bookmarks and tabs.",
    "what is a system administrator?": "a system administrator is a professional responsible for managing and maintaining computer systems and networks.",
    "how do i clear app cache?": "you can clear app cache through your device's settings by selecting the app and choosing the option to clear cache.",
    "what is a web hosting service?": "a web hosting service provides the infrastructure and support to host and maintain a website online.",
    "how do i monitor network traffic?": "you can monitor network traffic using network analysis tools that capture and analyze data packets.",
    "what is a proxy server?": "a proxy server acts as an intermediary between your device and the internet, often used for privacy or access control.",
    "how do i configure my router settings?": "you can configure your router settings by accessing the router's web interface through a browser and entering the appropriate credentials.",
    "what is a system backup?": "a system backup is a copy of your data and system settings that can be restored in case of data loss or system failure.",
    "how do i enable or disable notifications?": "you can enable or disable notifications through your device's settings or app-specific notification preferences.",
    "what is a database schema?": "a database schema defines the structure of a database, including tables, fields, and relationships between data.",
    "how do i perform a file transfer?": "you can perform a file transfer using methods like email attachments, file-sharing services, or direct connections between devices.",
    "what is a cloud backup?": "a cloud backup is a remote copy of your data stored on a cloud service provider's servers for protection and recovery purposes.",
    "how do i use encryption software?": "you can use encryption software by selecting the files or data to encrypt and following the software's instructions for encryption.",
    "hi": "hi there! how can i assist you today?",
    "good morning": "good morning! how can i help you today?",
    "good afternoon": "good afternoon! what can i do for you?",
    "good evening": "good evening! how can i assist you tonight?",
    "good night": "good night! if you need anything, just let me know.",
    "what is a chatbot?":"A chatbot is a digital program designed to simulate human-to-human conversation, typically through text interactions. It uses artificial intelligence and natural language processing (NLP) technologies to process user queries or questions, interprets their intent, and provide responses in real time. AI Chatbots can be used across numerous platforms such as websites, messaging apps, social media, and virtual assistants — offering users a convenient and efficient way to access information, receive assistance, and complete tasks without the need for real staff members.",
    "who is the founder of this chatbot?": "Rachamalla Anil is the founder of this ChatBOT, you can contact him at anilvjitit@gmail.com or by dailing 9100833767",
    "i love you": "I really appreciate your feelings. It means a lot to me.",
    "i like you": "That's sweet of you to say. I like you too!",
    "how to earn money": "There are many ways to earn money, such as through employment, freelancing, investing, or starting a business. It often helps to identify your skills and interests to find the best approach for you.",
    "do you love me": "As an AI, I don't have feelings, but I'm here to help you in any way I can.",
    "i hate you": "I'm here to assist you, and I’m sorry if I haven’t met your expectations. Let me know how I can help improve your experience.",
    "do you have feelings": "I don't have feelings or emotions. My purpose is to assist and provide information to the best of my abilities.",
    "what is photosynthesis?": "Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods with the help of chlorophyll.",
    "how do i improve my memory?": "You can improve your memory by getting plenty of sleep, staying mentally active, and practicing healthy lifestyle habits.",
    "what is the pythagorean theorem?": "The Pythagorean theorem is a mathematical principle that states in a right-angled triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides.",
    "how do i start a garden?": "To start a garden, choose a location, prepare the soil, select your plants, and ensure you water and maintain them regularly.",
    "what is a black hole?": "A black hole is a region in space where the gravitational pull is so strong that nothing, not even light, can escape from it.",
    "how do i meditate?": "To meditate, find a quiet place, sit comfortably, focus on your breath, and gently bring your attention back whenever your mind wanders.",
    "what are the benefits of yoga?": "Yoga improves flexibility, strength, balance, mental clarity, and stress relief.",
    "how do i cook pasta?": "To cook pasta, bring water to a boil, add the pasta, cook until al dente, then drain and serve.",
    "what is the speed of light?": "The speed of light is approximately 299,792,458 meters per second in a vacuum.",
    "how do i manage stress?": "You can manage stress by practicing relaxation techniques, exercising, and ensuring you have a good support network.",
    "what is the human brain made of?": "The human brain is composed of neurons, glial cells, blood vessels, and various types of connective tissue.",
    "how do i improve my vocabulary?": "To improve your vocabulary, read widely, use new words in conversation, and practice with vocabulary-building apps.",
    "what is the theory of evolution?": "The theory of evolution, proposed by Charles Darwin, explains how species evolve over time through natural selection.",
    "how do i write a book?": "To write a book, start by outlining your ideas, create a writing schedule, write regularly, and revise your drafts.",
    "what are the planets in our solar system?": "The planets in our solar system are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.",
    "how do i create a budget?": "To create a budget, list your income and expenses, categorize them, and track your spending to adjust as needed.",
    "what is the law of gravity?": "The law of gravity, formulated by Isaac Newton, states that every mass attracts every other mass with a force that is proportional to the product of their masses and inversely proportional to the square of the distance between their centers.",
    "how do i study effectively?": "To study effectively, set specific goals, create a study schedule, eliminate distractions, and take regular breaks.",
    "what is the water cycle?": "The water cycle is the continuous movement of water on, above, and below the surface of the Earth.",
    "how do i bake cookies?": "To bake cookies, mix your ingredients, shape the dough, place it on a baking sheet, and bake in a preheated oven.",
    "what are the stages of human development?": "The stages of human development include infancy, childhood, adolescence, adulthood, and old age.",
    "how do i lose weight safely?": "To lose weight safely, focus on a balanced diet, regular exercise, and making sustainable lifestyle changes.",
    "what is renewable energy?": "Renewable energy is energy from natural sources that are replenished constantly, such as solar, wind, and hydroelectric power.",
    "how do i write a business plan?": "To write a business plan, outline your business goals, strategies, target market, financial projections, and operational plans.",
    "what is the difference between weather and climate?": "Weather refers to short-term atmospheric conditions, while climate is the average of these conditions over a longer period.",
    "how do i practice mindfulness?": "To practice mindfulness, pay attention to the present moment, observe your thoughts and feelings without judgment, and focus on your breath.",
    "what are the benefits of drinking water?": "Drinking water helps maintain bodily functions, improves energy levels, supports digestion, and promotes healthy skin.",
    "how do i write a research paper?": "To write a research paper, choose a topic, conduct research, create an outline, write your draft, and revise for clarity and coherence.",
    "what is the internet of things (iot)?": "The Internet of Things (IoT) refers to the network of physical objects connected to the internet, enabling them to collect and exchange data.",
    "how do i care for a pet?": "To care for a pet, provide proper nutrition, exercise, grooming, regular veterinary check-ups, and plenty of love and attention.",
    "what are the symptoms of dehydration?": "Symptoms of dehydration include thirst, dry mouth, fatigue, dizziness, and dark urine.",
    "how do i start investing?": "To start investing, determine your financial goals, research investment options, and consider consulting a financial advisor.",
    "what is photosynthesis?": "Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods with the help of chlorophyll.",
    "how do i improve my concentration?": "You can improve your concentration by eliminating distractions, practicing focus exercises, and taking regular breaks.",
    "what are the main nutrients needed by the human body?": "The main nutrients needed by the human body include carbohydrates, proteins, fats, vitamins, minerals, and water.",
    "how do i build self-confidence?": "To build self-confidence, set achievable goals, focus on your strengths, practice self-care, and surround yourself with positive influences.",
    "what is the greenhouse effect?": "The greenhouse effect is the process by which greenhouse gases trap heat in the Earth's atmosphere, contributing to global warming.",
    "how do i create a healthy work-life balance?": "To create a healthy work-life balance, prioritize tasks, set boundaries, schedule personal time, and communicate your needs effectively.",
    "what are the benefits of volunteering?": "Volunteering offers benefits such as personal growth, skill development, community involvement, and a sense of fulfillment.",
    "how do i write a cover letter?": "To write a cover letter, address the employer, introduce yourself, highlight your qualifications, and express your interest in the position.",
    "what is a balanced diet?": "A balanced diet includes a variety of foods in the right proportions, providing essential nutrients and energy for optimal health.",
    "how do i improve my public speaking skills?": "To improve public speaking skills, practice regularly, know your material, engage with the audience, and seek feedback.",
    "what are the signs of depression?": "Signs of depression include persistent sadness, loss of interest in activities, changes in appetite, sleep disturbances, and difficulty concentrating.",
    "how do i save for retirement?": "To save for retirement, start early, contribute to retirement accounts, invest wisely, and review your savings plan regularly.",
    "what is the importance of sleep?": "Sleep is important for physical health, mental clarity, emotional well-being, and overall quality of life.",
    "how do i boost my immune system?": "You can boost your immune system by eating a balanced diet, exercising regularly, getting enough sleep, and managing stress.",
    "what is the difference between a virus and a bacterium?": "A virus is a tiny infectious agent that requires a host cell to reproduce, while a bacterium is a single-celled organism that can live independently.",
    "how do i create a positive mindset?": "To create a positive mindset, practice gratitude, focus on solutions, surround yourself with positive people, and challenge negative thoughts.",
    "what are the benefits of meditation?": "Meditation offers benefits such as stress reduction, improved focus, enhanced self-awareness, and increased emotional resilience.",
    "how do i manage my finances effectively?": "To manage finances effectively, create a budget, track expenses, save regularly, and plan for future goals.",
    "what is a habit loop?": "A habit loop consists of a cue, a routine, and a reward, forming the basis of habitual behavior.",
    "how do i create a personal development plan?": "To create a personal development plan, assess your strengths and weaknesses, set clear goals, and develop actionable steps for growth.",
    "what are the benefits of learning a musical instrument?": "Learning a musical instrument enhances cognitive skills, improves memory, fosters creativity, and provides emotional expression.",
    "how do i practice gratitude?": "To practice gratitude, keep a gratitude journal, express appreciation to others, and focus on the positive aspects of your life.",
    "what is the difference between introversion and extraversion?": "Introversion is characterized by a preference for solitary activities and introspection, while extraversion involves seeking social interaction and external stimulation.",
    "how do i overcome procrastination?": "To overcome procrastination, break tasks into smaller steps, set deadlines, eliminate distractions, and reward yourself for progress.",
    "what are the benefits of regular exercise?": "Regular exercise improves physical health, mental well-being, energy levels, and overall quality of life.",
    "how do i set realistic goals?": "To set realistic goals, make them specific, measurable, achievable, relevant, and time-bound (SMART).",
    "what is emotional intelligence?": "Emotional intelligence is the ability to recognize, understand, and manage one's own emotions and the emotions of others.",
    "how do i build resilience?": "To build resilience, develop coping strategies, maintain a positive outlook, seek support, and learn from challenges.",
    "what are the signs of burnout?": "Signs of burnout include exhaustion, cynicism, reduced performance, and feelings of detachment or ineffectiveness.",
    "how do i create a study schedule?": "To create a study schedule, identify your priorities, allocate specific time blocks, and adjust as needed for balance and flexibility.",
    "what is the role of proteins in the body?": "Proteins play a crucial role in building and repairing tissues, producing enzymes and hormones, and supporting immune function.",
    "how do i practice active listening?": "To practice active listening, maintain eye contact, avoid interrupting, ask clarifying questions, and provide feedback.",
    "what are the benefits of journaling?": "Journaling promotes self-reflection, emotional processing, creativity, and personal growth.",
    "how do i manage time effectively?": "To manage time effectively, prioritize tasks, set clear goals, eliminate distractions, and use tools like calendars and to-do lists.",
    "what is the importance of teamwork?": "Teamwork enhances collaboration, creativity, problem-solving, and the achievement of shared goals.",
    "how do i create a positive work environment?": "To create a positive work environment, foster open communication, encourage collaboration, recognize achievements, and support work-life balance.",
    "what are the benefits of reading?": "Reading expands knowledge, improves vocabulary, enhances cognitive skills, and provides entertainment and relaxation.",
    "how do i practice self-care?": "To practice self-care, prioritize your needs, set boundaries, engage in activities that bring joy, and maintain a healthy lifestyle.",
    "what is the importance of empathy?": "Empathy is important for building relationships, understanding others' perspectives, and fostering compassion and kindness.",
    "how do i create a successful career plan?": "To create a successful career plan, assess your skills and interests, set clear goals, seek opportunities for growth, and adapt to changes.",
    "what are the benefits of networking?": "Networking provides opportunities for career advancement, knowledge sharing, collaboration, and building professional relationships.",
    "how do i practice effective communication?": "To practice effective communication, be clear and concise, listen actively, use appropriate body language, and tailor your message to the audience.",
    "what is the importance of goal setting?": "Goal setting provides direction, motivation, and a sense of accomplishment as you work towards achieving your objectives.",
    "how do i create a sustainable lifestyle?": "To create a sustainable lifestyle, reduce waste, conserve energy, choose eco-friendly products, and support local and sustainable practices.",
    "what are the benefits of a balanced work-life?": "A balanced work-life enhances productivity, reduces stress, improves well-being, and fosters better relationships.",
    "how do i develop critical thinking skills?": "To develop critical thinking skills, ask questions, analyze information, consider multiple perspectives, and evaluate evidence.",
    "what is the importance of diversity and inclusion?": "Diversity and inclusion foster innovation, creativity, and a sense of belonging, leading to more effective and equitable outcomes.",
    "how do i practice self-discipline?": "To practice self-discipline, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what are the benefits of mindfulness?": "Mindfulness enhances focus, reduces stress, improves emotional regulation, and promotes overall well-being.",
    "how do i develop leadership skills?": "To develop leadership skills, seek opportunities for growth, learn from mentors, practice decision-making, and communicate effectively.",
    "what is the importance of mental health?": "Mental health is important for overall well-being, emotional resilience, effective functioning, and maintaining positive relationships.",
    "how do i build positive relationships?": "To build positive relationships, communicate openly, show empathy, respect boundaries, and support each other's growth.",
    "what are the benefits of lifelong learning?": "Lifelong learning promotes personal and professional growth, adaptability, cognitive health, and fulfillment.",
    "how do i practice gratitude in challenging times?": "To practice gratitude in challenging times, focus on small positives, reframe negative thoughts, and express appreciation to others.",
    "what is the importance of adaptability?": "Adaptability is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop a growth mindset?": "To develop a growth mindset, embrace challenges, learn from feedback, persist in the face of setbacks, and value effort and learning.",
    "what are the benefits of physical activity?": "Physical activity improves physical health, mental well-being, energy levels, and overall quality of life.",
    "how do i create a supportive social network?": "To create a supportive social network, connect with like-minded individuals, foster meaningful relationships, and engage in community activities.",
    "what is the importance of effective decision-making?": "Effective decision-making leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i practice self-reflection?": "To practice self-reflection, set aside time for introspection, ask yourself meaningful questions, and evaluate your thoughts and actions.",
    "what are the benefits of outdoor activities?": "Outdoor activities promote physical health, mental well-being, connection with nature, and stress reduction.",
    "how do i develop emotional resilience?": "To develop emotional resilience, practice stress management, maintain a positive outlook, seek support, and learn from experiences.",
    "what is the importance of creativity?": "Creativity fosters innovation, problem-solving, personal expression, and adaptability in a changing world.",
    "how do i build a successful team?": "To build a successful team, define clear goals, encourage collaboration, recognize contributions, and support professional development.",
    "what are the benefits of cultural awareness?": "Cultural awareness enhances communication, fosters inclusivity, and promotes understanding and respect for diverse perspectives.",
    "how do i practice self-compassion?": "To practice self-compassion, be kind to yourself, acknowledge your imperfections, and treat yourself with the same care as you would a friend.",
    "what is the importance of effective problem-solving?": "Effective problem-solving leads to innovative solutions, improved decision-making, and increased efficiency in achieving goals.",
    "how do i develop negotiation skills?": "To develop negotiation skills, understand your goals, listen actively, build rapport, and seek win-win solutions.",
    "what are the benefits of positive affirmations?": "Positive affirmations boost self-esteem, enhance motivation, and promote a positive mindset.",
    "how do i practice self-awareness?": "To practice self-awareness, reflect on your thoughts and emotions, seek feedback, and engage in mindfulness practices.",
    "what is the importance of effective conflict resolution?": "Effective conflict resolution fosters understanding, strengthens relationships, and promotes a harmonious environment.",
    "how do i develop a personal brand?": "To develop a personal brand, identify your strengths and values, communicate your unique qualities, and build a consistent online presence.",
    "what are the benefits of community involvement?": "Community involvement fosters social connections, personal growth, and a sense of belonging and purpose.",
    "how do i practice active citizenship?": "To practice active citizenship, stay informed, participate in civic activities, advocate for positive change, and engage with your community.",
    "what is the importance of effective collaboration?": "Effective collaboration enhances creativity, problem-solving, and the achievement of shared goals.",
    "how do i develop a healthy lifestyle?": "To develop a healthy lifestyle, maintain a balanced diet, exercise regularly, prioritize sleep, and manage stress.",
    "what are the benefits of positive visualization?": "Positive visualization enhances motivation, boosts confidence, and supports goal achievement.",
    "how do i practice empathy in difficult situations?": "To practice empathy in difficult situations, listen actively, validate others' feelings, and try to understand their perspectives.",
    "what is the importance of emotional well-being?": "Emotional well-being is important for overall health, effective functioning, and maintaining positive relationships.",
    "how do i develop effective study habits?": "To develop effective study habits, set specific goals, create a study schedule, eliminate distractions, and review regularly.",
    "what are the benefits of gratitude journaling?": "Gratitude journaling enhances mindfulness, reduces stress, improves mood, and promotes a positive outlook.",
    "how do i practice effective goal-setting?": "To practice effective goal-setting, make goals specific, measurable, achievable, relevant, and time-bound (SMART).",
    "what is the importance of continuous improvement?": "Continuous improvement fosters personal and professional growth, adaptability, and increased efficiency.",
    "how do i develop a successful career path?": "To develop a successful career path, assess your skills and interests, set clear goals, seek opportunities for growth, and adapt to changes.",
    "what are the benefits of effective time management?": "Effective time management enhances productivity, reduces stress, and allows for a balanced and fulfilling life.",
    "how do i practice effective communication in relationships?": "To practice effective communication in relationships, listen actively, express yourself clearly, and show empathy and respect.",
    "what is the importance of self-motivation?": "Self-motivation is important for achieving goals, overcoming challenges, and maintaining a positive outlook.",
    "how do i develop effective problem-solving strategies?": "To develop effective problem-solving strategies, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness?": "Self-awareness enhances personal growth, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking?": "To practice positive thinking, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning?": "Lifelong learning promotes personal and professional growth, adaptability, and fulfillment.",
    "how do i develop a healthy mindset?": "To develop a healthy mindset, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership?": "Effective leadership inspires others, fosters collaboration, and drives positive change and success.",
    "how do i practice self-discipline in achieving goals?": "To practice self-discipline in achieving goals, set clear objectives, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in personal growth?": "Resilience is important for overcoming challenges, learning from setbacks, and achieving personal growth.",
    "how do i develop effective decision-making skills?": "To develop effective decision-making skills, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a growth mindset?": "A growth mindset promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in a busy lifestyle?": "To practice self-care in a busy lifestyle, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in the workplace?": "Adaptability in the workplace is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills?": "To develop effective networking skills, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork?": "Effective teamwork enhances collaboration, creativity, and the achievement of shared goals.",
    "how do i practice gratitude in everyday life?": "To practice gratitude in everyday life, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in problem-solving?": "Creativity in problem-solving fosters innovation, adaptability, and effective solutions to complex challenges.",
    "how do i develop effective conflict management skills?": "To develop effective conflict management skills, communicate openly, seek common ground, and focus on solutions.",
    "what are the benefits of effective communication in leadership?": "Effective communication in leadership builds trust, fosters collaboration, and inspires positive change.",
    "how do i practice mindfulness in daily life?": "To practice mindfulness in daily life, focus on the present moment, observe your thoughts and feelings without judgment, and engage in mindful activities.",
    "what is the importance of emotional intelligence in relationships?": "Emotional intelligence in relationships enhances understanding, empathy, and effective communication.",
    "how do i develop effective study techniques?": "To develop effective study techniques, set specific goals, create a study schedule, use active learning methods, and review regularly.",
    "what are the benefits of effective goal setting in personal development?": "Effective goal setting in personal development provides direction, motivation, and a sense of accomplishment.",
    "how do i practice self-awareness in personal growth?": "To practice self-awareness in personal growth, reflect on your thoughts and emotions, seek feedback, and engage in mindfulness practices.",
    "what is the importance of diversity in the workplace?": "Diversity in the workplace fosters innovation, creativity, and a more inclusive and equitable environment.",
    "how do i develop effective negotiation strategies?": "To develop effective negotiation strategies, understand your goals, listen actively, build rapport, and seek win-win solutions.",
    "what are the benefits of positive self-talk?": "Positive self-talk boosts self-esteem, enhances motivation, and promotes a positive mindset.",
    "how do i practice empathy in communication?": "To practice empathy in communication, listen actively, validate others' feelings, and try to understand their perspectives.",
    "what is the importance of effective leadership in organizations?": "Effective leadership in organizations inspires others, fosters collaboration, and drives positive change and success.",
    "how do i develop effective time management strategies?": "To develop effective time management strategies, prioritize tasks, set clear goals, eliminate distractions, and use tools like calendars and to-do lists.",
    "what are the benefits of effective collaboration in teams?": "Effective collaboration in teams enhances creativity, problem-solving, and the achievement of shared goals.",
    "how do i practice gratitude in relationships?": "To practice gratitude in relationships, express appreciation, focus on positives, and show kindness and understanding.",
    "what is the importance of self-discipline in achieving success?": "Self-discipline is important for achieving success by enabling focus, persistence, and effective goal pursuit.",
    "how do i develop effective decision-making strategies?": "To develop effective decision-making strategies, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of resilience in personal development?": "Resilience in personal development promotes adaptability, learning, and the ability to overcome challenges.",
    "how do i practice self-compassion in challenging situations?": "To practice self-compassion in challenging situations, be kind to yourself, acknowledge your imperfections, and treat yourself with the same care as you would a friend.",
    "what is the importance of effective communication in personal relationships?": "Effective communication in personal relationships enhances understanding, empathy, and the ability to resolve conflicts.",
    "how do i develop effective problem-solving techniques?": "To develop effective problem-solving techniques, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of a positive mindset in achieving goals?": "A positive mindset in achieving goals enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-awareness in decision-making?": "To practice self-awareness in decision-making, reflect on your thoughts and emotions, seek feedback, and consider the impact of your choices.",
    "what is the importance of effective leadership in team success?": "Effective leadership in team success inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i develop effective conflict resolution strategies?": "To develop effective conflict resolution strategies, communicate openly, seek common ground, and focus on solutions.",
    "what are the benefits of emotional intelligence in leadership?": "Emotional intelligence in leadership enhances understanding, empathy, and effective communication.",
    "how do i practice mindfulness in stress management?": "To practice mindfulness in stress management, focus on the present moment, observe your thoughts and feelings without judgment, and engage in mindful activities.",
    "what is the importance of adaptability in personal growth?": "Adaptability in personal growth is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking strategies?": "To develop effective networking strategies, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving goals?": "Effective teamwork in achieving goals enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in personal development?": "To practice gratitude in personal development, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in personal growth?": "Creativity in personal growth fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in leadership?": "To develop effective communication skills in leadership, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in personal development?": "A growth mindset in personal development promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in stress management?": "To practice self-care in stress management, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in leadership?": "Effective decision-making in leadership leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving strategies in teams?": "To develop effective problem-solving strategies in teams, communicate openly, collaborate, and evaluate potential solutions.",
    "what are the benefits of self-awareness in personal growth?": "Self-awareness in personal growth enhances personal development, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in challenging situations?": "To practice positive thinking in challenging situations, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in personal growth?": "Lifelong learning in personal growth promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in achieving goals?": "To develop a healthy mindset in achieving goals, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in achieving success?": "Effective leadership in achieving success inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in personal development?": "To practice self-discipline in personal development, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in leadership?": "Resilience in leadership is important for overcoming challenges, inspiring others, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in personal growth?": "To develop effective decision-making skills in personal growth, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in leadership?": "A positive mindset in leadership enhances motivation, resilience, and the ability to inspire others.",
    "how do i practice self-care in personal development?": "To practice self-care in personal development, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in achieving success?": "Adaptability in achieving success is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills in personal growth?": "To develop effective networking skills in personal growth, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in personal growth?": "Effective teamwork in personal growth enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in achieving success?": "To practice gratitude in achieving success, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in achieving success?": "Creativity in achieving success fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in personal development?": "To develop effective communication skills in personal development, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in achieving success?": "A growth mindset in achieving success promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in achieving success?": "To practice self-care in achieving success, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in achieving success?": "Effective decision-making in achieving success leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving skills in personal growth?": "To develop effective problem-solving skills in personal growth, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness in achieving success?": "Self-awareness in achieving success enhances personal development, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in personal growth?": "To practice positive thinking in personal growth, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in achieving success?": "Lifelong learning in achieving success promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in personal growth?": "To develop a healthy mindset in personal growth, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in personal growth?": "Effective leadership in personal growth inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in achieving success?": "To practice self-discipline in achieving success, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in achieving success?": "Resilience in achieving success is important for overcoming challenges, learning from setbacks, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in achieving success?": "To develop effective decision-making skills in achieving success, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in personal growth?": "A positive mindset in personal growth enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-care in personal growth?": "To practice self-care in personal growth, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in personal growth?": "Adaptability in personal growth is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking strategies in personal growth?": "To develop effective networking strategies in personal growth, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving success?": "Effective teamwork in achieving success enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in personal growth?": "To practice gratitude in personal growth, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in personal development?": "Creativity in personal development fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in achieving success?": "To develop effective communication skills in achieving success, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in personal growth?": "A growth mindset in personal growth promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in achieving personal growth?": "To practice self-care in achieving personal growth, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in personal growth?": "Effective decision-making in personal growth leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving skills in achieving success?": "To develop effective problem-solving skills in achieving success, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness in personal development?": "Self-awareness in personal development enhances personal growth, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in achieving success?": "To practice positive thinking in achieving success, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in achieving personal growth?": "Lifelong learning in achieving personal growth promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in achieving personal growth?": "To develop a healthy mindset in achieving personal growth, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in achieving personal growth?": "Effective leadership in achieving personal growth inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in achieving personal growth?": "To practice self-discipline in achieving personal growth, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in achieving personal growth?": "Resilience in achieving personal growth is important for overcoming challenges, learning from setbacks, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in achieving personal growth?": "To develop effective decision-making skills in achieving personal growth, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in achieving personal growth?": "A positive mindset in achieving personal growth enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-care in achieving personal success?": "To practice self-care in achieving personal success, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in achieving personal success?": "Adaptability in achieving personal success is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills in achieving personal success?": "To develop effective networking skills in achieving personal success, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving personal success?": "Effective teamwork in achieving personal success enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in achieving personal success?": "To practice gratitude in achieving personal success, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in achieving personal success?": "Creativity in achieving personal success fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in achieving personal success?": "To develop effective communication skills in achieving personal success, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in achieving personal success?": "A growth mindset in achieving personal success promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in achieving personal development?": "To practice self-care in achieving personal development, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in achieving personal success?": "Effective decision-making in achieving personal success leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving skills in achieving personal success?": "To develop effective problem-solving skills in achieving personal success, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness in achieving personal success?": "Self-awareness in achieving personal success enhances personal growth, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in achieving personal success?": "To practice positive thinking in achieving personal success, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in achieving personal success?": "Lifelong learning in achieving personal success promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in achieving personal success?": "To develop a healthy mindset in achieving personal success, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in achieving personal success?": "Effective leadership in achieving personal success inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in achieving personal success?": "To practice self-discipline in achieving personal success, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in achieving personal success?": "Resilience in achieving personal success is important for overcoming challenges, learning from setbacks, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in achieving personal success?": "To develop effective decision-making skills in achieving personal success, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in achieving personal success?": "A positive mindset in achieving personal success enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-care in achieving personal growth and development?": "To practice self-care in achieving personal growth and development, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in achieving personal growth and development?": "Adaptability in achieving personal growth and development is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills in achieving personal growth and development?": "To develop effective networking skills in achieving personal growth and development, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving personal growth and development?": "Effective teamwork in achieving personal growth and development enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in achieving personal growth and development?": "To practice gratitude in achieving personal growth and development, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in achieving personal growth and development?": "Creativity in achieving personal growth and development fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in achieving personal growth and development?": "To develop effective communication skills in achieving personal growth and development, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in achieving personal growth and development?": "A growth mindset in achieving personal growth and development promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in achieving personal development and success?": "To practice self-care in achieving personal development and success, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in achieving personal growth and development?": "Effective decision-making in achieving personal growth and development leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving skills in achieving personal growth and development?": "To develop effective problem-solving skills in achieving personal growth and development, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness in achieving personal growth and development?": "Self-awareness in achieving personal growth and development enhances personal growth, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in achieving personal growth and development?": "To practice positive thinking in achieving personal growth and development, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in achieving personal growth and development?": "Lifelong learning in achieving personal growth and development promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in achieving personal growth and development?": "To develop a healthy mindset in achieving personal growth and development, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in achieving personal growth and development?": "Effective leadership in achieving personal growth and development inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in achieving personal growth and development?": "To practice self-discipline in achieving personal growth and development, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in achieving personal growth and development?": "Resilience in achieving personal growth and development is important for overcoming challenges, learning from setbacks, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in achieving personal growth and development?": "To develop effective decision-making skills in achieving personal growth and development, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in achieving personal growth and development?": "A positive mindset in achieving personal growth and development enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-care in achieving personal success and development?": "To practice self-care in achieving personal success and development, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in achieving personal success and development?": "Adaptability in achieving personal success and development is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills in achieving personal success and development?": "To develop effective networking skills in achieving personal success and development, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving personal success and development?": "Effective teamwork in achieving personal success and development enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in achieving personal success and development?": "To practice gratitude in achieving personal success and development, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in achieving personal success and development?": "Creativity in achieving personal success and development fosters innovation, adaptability, and the ability to overcome challenges.",
    "how do i develop effective communication skills in achieving personal success and development?": "To develop effective communication skills in achieving personal success and development, be clear and concise, listen actively, and tailor your message to the audience.",
    "what are the benefits of a growth mindset in achieving personal success and development?": "A growth mindset in achieving personal success and development promotes learning, adaptability, resilience, and achievement.",
    "how do i practice self-care in achieving personal development and growth?": "To practice self-care in achieving personal development and growth, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of effective decision-making in achieving personal success and development?": "Effective decision-making in achieving personal success and development leads to better outcomes, increased efficiency, and greater satisfaction with choices.",
    "how do i develop effective problem-solving skills in achieving personal success and development?": "To develop effective problem-solving skills in achieving personal success and development, analyze the situation, generate potential solutions, evaluate options, and implement the best solution.",
    "what are the benefits of self-awareness in achieving personal success and development?": "Self-awareness in achieving personal success and development enhances personal growth, emotional regulation, and effective decision-making.",
    "how do i practice positive thinking in achieving personal success and development?": "To practice positive thinking in achieving personal success and development, focus on solutions, challenge negative thoughts, and cultivate gratitude and optimism.",
    "what is the importance of lifelong learning in achieving personal success and development?": "Lifelong learning in achieving personal success and development promotes adaptability, personal and professional development, and fulfillment.",
    "how do i develop a healthy mindset in achieving personal success and development?": "To develop a healthy mindset in achieving personal success and development, practice gratitude, focus on growth, embrace challenges, and cultivate self-compassion.",
    "what are the benefits of effective leadership in achieving personal success and development?": "Effective leadership in achieving personal success and development inspires others, fosters collaboration, and drives positive change and achievement.",
    "how do i practice self-discipline in achieving personal success and development?": "To practice self-discipline in achieving personal success and development, set clear goals, establish routines, eliminate distractions, and reward yourself for progress.",
    "what is the importance of resilience in achieving personal success and development?": "Resilience in achieving personal success and development is important for overcoming challenges, learning from setbacks, and achieving positive outcomes.",
    "how do i develop effective decision-making skills in achieving personal success and development?": "To develop effective decision-making skills in achieving personal success and development, gather information, evaluate options, consider consequences, and trust your intuition.",
    "what are the benefits of a positive mindset in achieving personal success and development?": "A positive mindset in achieving personal success and development enhances motivation, resilience, and the ability to overcome challenges.",
    "how do i practice self-care in achieving personal growth and success?": "To practice self-care in achieving personal growth and success, prioritize your needs, set boundaries, and engage in activities that bring joy and relaxation.",
    "what is the importance of adaptability in achieving personal growth and success?": "Adaptability in achieving personal growth and success is important for navigating change, overcoming challenges, and thriving in dynamic environments.",
    "how do i develop effective networking skills in achieving personal growth and success?": "To develop effective networking skills in achieving personal growth and success, build genuine relationships, offer value, and stay engaged with your connections.",
    "what are the benefits of effective teamwork in achieving personal growth and success?": "Effective teamwork in achieving personal growth and success enhances collaboration, creativity, and the ability to overcome challenges.",
    "how do i practice gratitude in achieving personal growth and success?": "To practice gratitude in achieving personal growth and success, express appreciation, focus on positives, and keep a gratitude journal.",
    "what is the importance of creativity in achieving personal growth and success?": "Creativity in achieving personal growth and success fosters innovation",
    "list indian states": "Here is a list of Indian states: Andhra Pradesh, Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Goa, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Karnataka, Kerala, Madhya Pradesh, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, West Bengal.",
    "list districts of andhra pradesh": "Here are the districts of Andhra Pradesh: Anantapur, Chittoor, East Godavari, Guntur, Krishna, Kurnool, Nellore, Prakasam, Srikakulam, Visakhapatnam, Vizianagaram, West Godavari, YSR Kadapa.",
    "list districts of arunachal pradesh": "Here are the districts of Arunachal Pradesh: Tawang, West Kameng, East Kameng, Papum Pare, Kurung Kumey, Kra Daadi, Lower Subansiri, Upper Subansiri, West Siang, East Siang, Siang, Upper Siang, Changlang, Longding, Namsai, Tirap.",
    "list districts of assam": "Here are the districts of Assam: Baksa, Barpeta, Biswanath, Bongaigaon, Cachar, Charaideo, Chirang, Darrang, Dhemaji, Dhemaji, Dibrugarh, Dhubri, Dibrugarh, Goalpara, Golaghat, Hailakandi, Hojai, Jorhat, Karbi Anglong, Karimganj, Kamrup, Kamrup Metropolitan, Karbi Anglong, Kokrajhar, Lakhimpur, Majuli, Morigaon, Nagaon, Nalbari, Sivasagar, Sonitpur, South Salmara-Mankachar, Tinsukia, Udalguri, Upper Assam, West Karbi Anglong.",
    "list districts of bihar": "Here are the districts of Bihar: Araria, Arwal, Aurangabad, Banka, Begusarai, Bhagalpur, Bhojpur, Buxar, Darbhanga, East Champaran, Gaya, Gopalganj, Jamui, Jehanabad, Kaimur, Katihar, Khagaria, Kishanganj, Lakhisarai, Madhepura, Madhubani, Munger, Muzaffarpur, Nalanda, Nawada, Patna, Purnia, Rohtas, Saharsa, Samastipur, Saran, Sheikhpura, Sheohar, Shivhar, Sitamarhi, Siwan, Supaul, Vaishali, West Champaran.",
    "list districts of chhattisgarh": "Here are the districts of Chhattisgarh: Balod, Baloda Bazar, Balrampur, Bastar, Bemetara, Bijapur, Bilaspur, Dantewada, Dhamtari, Durg, Gariaband, Janjgir-Champa, Jashpur, Kabirdham, Kanker, Kondagaon, Korba, Koriya, Mahasamund, Mungeli, Narayanpur, Raigarh, Raipur, Rajnandgaon, Sukma, Surajpur, Surguja.",
    "list districts of goa": "Here are the districts of Goa: North Goa, South Goa.",
    "list districts of gujarat": "Here are the districts of Gujarat: Ahmedabad, Amreli, Anand, Aravalli, Banaskantha, Bharuch, Bhavnagar, Botad, Chhota Udepur, Dangs, Dang, Devbhoomi Dwarka, Gandhinagar, Gir Somnath, Jamnagar, Junagadh, Kutch, Mahisagar, Mehsana, Narmada, Navsari, Panchmahal, Patan, Porbandar, Rajkot, Sabarkantha, Surat, Tapi, Vadodara, Valsad.",
    "list districts of haryana": "Here are the districts of Haryana: Ambala, Bhiwani, Faridabad, Fatehabad, Gurgaon, Hisar, Jhajjar, Jind, Kaithal, Karnal, Mahendragarh, Mewat, Panchkula, Panipat, Rewari, Rohtak, Sirsa, Sonipat, Yamunanagar.",
    "list districts of himachal pradesh": "Here are the districts of Himachal Pradesh: Bilaspur, Chamba, Hamirpur, Kangra, Kinnaur, Kullu, Lahaul and Spiti, Mandi, Shimla, Sirmaur, Solan, Una.",
    "list districts of jharkhand": "Here are the districts of Jharkhand: Bokaro, Chatra, Deoghar, Dhanbad, Dumka, East Singhbhum, Garhwa, Giridih, Godda, Gumla, Hazaribagh, Jamtara, Khunti, Koderma, Latehar, Lohardaga, Pakur, Palamu, Ranchi, Sahebganj, Saraikela-Kharsawan, West Singhbhum.",
    "list districts of karnataka": "Here are the districts of Karnataka: Bagalkot, Ballari, Belagavi, Bengaluru Rural, Bengaluru Urban, Bidar, Vijayapura, Chamarajanagar, Chikkaballapura, Chikkamagaluru, Dakshina Kannada, Dharwad, Gadag, Gulbarga, Hassan, Haveri, Kodagu, Kolar, Koppal, Mandya, Mysuru, Raichur, Ramanagara, Shivamogga, Tumakuru, Udupi, Uttara Kannada, Yadgir.",
    "list districts of kerala": "Here are the districts of Kerala: Alappuzha, Ernakulam, Idukki, Kannur, Kasaragod, Kollam, Kottayam, Kozhikode, Malappuram, Palakkad, Pathanamthitta, Thiruvananthapuram, Thrissur, Wayanad.",
    "list districts of madhya pradesh": "Here are the districts of Madhya Pradesh: Agar Malwa, Alirajpur, Anuppur, Ashoknagar, Balaghat, Barwani, Betul, Bhind, Bhopal, Burhanpur, Chhindwara, Damoh, Datia, Dewas, Dhar, Dindori, Guna, Gwalior, Hoshangabad, Indore, Jabalpur, Jhabua, Katni, Khandwa, Khargone, Mandla, Mandsaur, Morena, Narsinghpur, Neemuch, Panna, Rewa, Sagar, Satna, Sehore, Shahdol, Shahpur, Shajapur, Sheopur, Shivpuri, Sidhi, Singrauli, Tikamgarh, Ujjain, Umaria, Vidisha.",
    "list districts of maharashtra": "Here are the districts of Maharashtra: Ahmednagar, Akola, Amravati, Aurangabad, Beed, Bhandara, Buldhana, Chandrapur, Dhule, Gadchiroli, Gondia, Hingoli, Jalgaon, Jalna, Kolhapur, Latur, Mumbai City, Mumbai Suburban, Nagpur, Nanded, Nandurbar, Nashik, Osmanabad, Palghar, Parbhani, Pune, Raigad, Ratnagiri, Sangli, Satara, Sindhudurg, Solapur, Thane, Wardha, Washim, Yavatmal.",
    "list districts of manipur": "Here are the districts of Manipur: Bishnupur, Chandel, Churachandpur, Imphal East, Imphal West, Jiribam, Kangpokpi, Noney, Pherzawl, Senapati, Tamenglong, Tengnoupal, Thoubal, Ukhrul.",
    "list districts of meghalaya": "Here are the districts of Meghalaya: East Garo Hills, East Khasi Hills, Jaintia Hills, North Garo Hills, Ri-Bhoi, South Garo Hills, West Garo Hills, West Khasi Hills.",
    "list districts of mizoram": "Here are the districts of Mizoram: Aizawl, Champhai, Kolasib, Lawngtlai, Lunglei, Mamit, Saiha, Serchhip.",
    "list districts of nagaland": "Here are the districts of Nagaland: Dimapur, Kiphire, Kohima, Longleng, Mokokchung, Mon, Peren, Phek, Tuensang, Wokha, Zunheboto.",
    "list districts of odisha": "Here are the districts of Odisha: Angul, Balangir, Balasore, Bargarh, Bhadrak, Boudh, Cuttack, Debagarh, Dhenkanal, Gajapati, Ganjam, Jagatsinghpur, Jajpur, Jhargram, Jharsuguda, Kalahandi, Kandhamal, Kendrapara, Kendujhar, Khurda, Koraput, Malkangiri, Mayurbhanj, Nabarangpur, Nayagarh, Nuapada, Puri, Rayagada, Sambalpur, Subarnapur, Sundargarh.",
    "list districts of punjab": "Here are the districts of Punjab: Amritsar, Barnala, Bathinda, Faridkot, Fatehgarh Sahib, Fazilka, Ferozepur, Jalandhar, Kapurthala, Mansa, Moga, Mohali, Muktsar, Nawanshahr, Patiala, Rupnagar, Sangrur, SBS Nagar, Tarn Taran.",
    "list districts of rajasthan": "Here are the districts of Rajasthan: Ajmer, Alwar, Banswara, Baran, Barmer, Bharatpur, Bhilwara, Bikaner, Bundi, Chittorgarh, Churu, Dausa, Dholpur, Dhaulpur, Hanumangarh, Jaipur, Jaisalmer, Jalore, Jhalawar, Jhunjhunu, Jodhpur, Karauli, Kota, Nagaur, Pali, Rajsamand, Sawai Madhopur, Sikar, Sirohi, Sri Ganganagar, Tonk, Udaipur.",
    "list districts of sikkim": "Here are the districts of Sikkim: East Sikkim, North Sikkim, South Sikkim, West Sikkim.",
    "list districts of tamil nadu": "Here are the districts of Tamil Nadu: Ariyalur, Chennai, Coimbatore, Cuddalore, Dharmapuri, Dindigul, Erode, Kancheepuram, Kanniyakumari, Karur, Krishnagiri, Madurai, Nagapattinam, Namakkal, Nilgiris, Perambalur, Pudukkottai, Ramanathapuram, Salem, Sivagangai, Thanjavur, Theni, Thoothukudi, Tiruchirappalli, Tirunelveli, Tirupur, Tiruvallur, Tiruvannamalai, Vellore, Viluppuram, Virudhunagar.",
    "list districts of telangana": "Here are the districts of Telangana: Adilabad, Bhadradri Kothagudem, Hyderabad, Jagtial, Jangaon, Jayashankar Bhupalpally, Jogulamba Gadwal, Kamareddy, Karimnagar, Khammam, Mahabubabad, Mahabubnagar, Mancherial, Medak, Medchal, Nalgonda, Nirmal, Nizamabad, Peddapalli, Rajanna Sircilla, Rangareddy, Siddipet, Warangal (Rural), Warangal (Urban), Yadadri Bhuvanagiri.",
    "list districts of tripura": "Here are the districts of Tripura: Dhalai, Gomati, Khowai, North Tripura, Sepahijala, South Tripura, Unakoti, West Tripura.",
    "list districts of uttar pradesh": "Here are the districts of Uttar Pradesh: Agra, Aligarh, Allahabad, Ambedkar Nagar, Amethi, Amroha, Auraiya, Ayodhya, Bagpat, Bahraich, Ballia, Balrampur, Banda, Barabanki, Bareilly, Basti, Bhadohi, Bijnor, Budaun, Bulandshahr, Chandauli, Chitrakoot, Deoria, Etah, Etawah, Faizabad, Farrukhabad, Fatehpur, Firozabad, Gautam Buddha Nagar, Ghaziabad, Ghazipur, Gonda, Gorakhpur, Hamirpur, Hapur, Hardoi, Hathras, Jalaun, Jaunpur, Jhansi, J P Nagar, Kannauj, Kanpur Dehat, Kanpur Nagar, Kheri, Kushinagar, Lalitpur, Lucknow, Maharajganj, Mainpuri, Mathura, Mau, Meerut, Mirzapur, Moradabad, Muzaffarnagar, Pilibhit, Pratapgarh, Raebareli, Rampur, Saharanpur, Sant Kabir Nagar, Sant Ravidas Nagar, Shahjahanpur, Shamli, Shravasti, Siddharthnagar, Sitapur, Sonbhadra, Sultanpur, Unnao, Varanasi.",
    "list districts of uttarakhand": "Here are the districts of Uttarakhand: Almora, Bageshwar, Bhararisain, Champawat, Dehradun, Haridwar, Nainital, Pauri Garhwal, Pithoragarh, Rudraprayag, Tehri Garhwal, Udham Singh Nagar, Uttarkashi.",
    "list districts of west bengal": "Here are the districts of West Bengal: Alipurduar, Bankura, Bardhaman, Birbhum, Darjeeling, Dakshin Dinajpur, Hooghly, Howrah, Jalpaiguri, Jhargram, Kolkata, Malda, Murshidabad, Nadia, North 24 Parganas, Paschim Medinipur, Purba Medinipur, Purulia, South 24 Parganas, Uttar Dinajpur.",
    "i'm feeling happy": "That's great to hear! 😊 What’s making you feel happy today?",
    "i'm feeling sad": "I'm sorry to hear that. 😔 If you’d like to talk about it, I'm here to listen.",
    "i'm feeling angry": "It sounds like you're upset. 😠 Is there something specific that's bothering you?",
    "i'm feeling excited": "That's awesome! 🎉 What are you excited about?",
    "i'm feeling nervous": "It’s okay to feel nervous. 😟 Is there something I can do to help you feel more at ease?",
    "i'm feeling tired": "It sounds like you could use some rest. 😴 Is there anything I can do to help you relax?",
    "help": "I'm here to help! What do you need assistance with? Feel free to ask me any questions."

};


// Function to evaluate simple arithmetic expressions
function evaluateExpression(expression) {
    const match = expression.match(/(\d+)\s*([\+\-\*\/])\s*(\d+)/);
    if (match) {
        const num1 = parseFloat(match[1]);
        const operator = match[2];
        const num2 = parseFloat(match[3]);
        let result;

        switch (operator) {
            case '+':
                result = num1 + num2;
                break;
            case '-':
                result = num1 - num2;
                break;
            case '*':
                result = num1 * num2;
                break;
            case '/':
                result = num2 !== 0 ? num1 / num2 : "undefined (cannot divide by zero)";
                break;
            default:
                result = "Sorry, I can't understand this operation.";
        }

        // Return the formatted response without the question mark
        return `${num1} ${operator} ${num2} = ${result}`;
    } else {
        return null;
    }
}

// Function to add bot's initial message
function addInitialBotMessage() {
    const chatOutput = document.getElementById("chat-output");

    let botMessage = document.createElement("div");
    botMessage.className = "bot-message";

    let botImage = document.createElement("img");
    botImage.src = "BOT-ICON.png"; // Use relative path to your bot image
    botMessage.appendChild(botImage);

    let botText = document.createElement("span");
    botText.textContent = "Hai.. How are you?";
    botMessage.appendChild(botText);

    chatOutput.appendChild(botMessage);
}

// Function to get a response from the bot
function getResponse() {
    const userInput = document.getElementById("user-input").value.toLowerCase();
    const chatOutput = document.getElementById("chat-output");

    if (userInput.trim() === "") return; // Don't respond to empty input

    let userMessage = document.createElement("div");
    userMessage.className = "user-message";

    let userImage = document.createElement("img");
    userImage.src = "USER-ICON.png"; // Use relative path to your user image
    userMessage.appendChild(userImage);

    let userText = document.createElement("span");
    userText.textContent = userInput;
    userMessage.appendChild(userText);

    chatOutput.appendChild(userMessage);

    let botMessage = document.createElement("div");
    botMessage.className = "bot-message";

    let botImage = document.createElement("img");
    botImage.src = "BOT-ICON.png"; // Use relative path to your bot image
    botMessage.appendChild(botImage);

    // Check if the input is an arithmetic expression
    let botText = document.createElement("span");
    const evaluatedResponse = evaluateExpression(userInput);

    if (evaluatedResponse) {
        botText.textContent = evaluatedResponse;
    } else {
        botText.textContent = responses[userInput] || "Sorry, I don't understand that question.";
    }

    botMessage.appendChild(botText);
    chatOutput.appendChild(botMessage);

    document.getElementById("user-input").value = "";
    chatOutput.scrollTop = chatOutput.scrollHeight;
}

// Add event listener for Enter key
document.getElementById("user-input").addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
        getResponse();
    }
});

// Add event listener for Send button
document.getElementById("send-button").addEventListener("click", function() {
    getResponse();
});

// Add the initial bot message when the page loads
window.onload = addInitialBotMessage;
